### ISSUE TITLE
Copy/paste text confusion?

### ISSUE THREAD

**Issue by helenginn** [taw10/colloquium#1]
1. Open demo.sc
2. Open the second slide
3. Click the frame, "Editing slides works how..."
4. Edit > Copy frame
5. Edit > Paste (doesn't work, nothing happens?)
alternatively,
5a. Ctrl+V (get a second frame inside the first frame with the same offset from the top left corner.
5b. Ctrl+V again (Segmentation fault).
Screenshot attached just after 5a.

![screenshot from 2018-04-16 16-24-19](https://user-images.githubusercontent.com/1901917/38819203-aecc4cc0-4192-11e8-97b5-19d99a035266.png)

n.b. unsure how this feature is meant to work!

**Comment by taw10** [comment]
Cut and paste, including to/from other programs, has been tidied up a lot in commit e7bd118532.  Still a work in progress, though, but your test case now works properly.
